apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: arkime-oauth2-proxy
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - arkime-{{ .Values.ctf }}.gartenverein-tackenberg.de
  rules:
    - host: arkime-{{ .Values.ctf }}.gartenverein-tackenberg.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: arkime-oauth2-proxy
                port:
                  name: http
