node-name: ...
server: https://gartenverein-tackenberg.de:6443
node-label:
  - ctfr.attacking-lab.com/role=infra
  # TODO: Adjust for the ctf for which the router is used
  # - ctfr.attacking-lab.com/ctf=ecsc-staging
node-taint:
  - ctfr.attacking-lab.com/role=infra:NoExecute
  # TODO: Adjust for the ctf for which the router is used
  # - ctfr.attacking-lab.com/ctf=ecsc-staging:NoExecute
