# These stubes where generated (and manually completed) based on
# python3-nftables/stable,now 1.0.6-2+deb12u2 amd64
# from the debian apt repos.

from ctypes import *  # noqa
from typing import Any, Iterable

from _typeshed import Incomplete

NFTABLES_VERSION: str

class SchemaValidator:
    schema: str
    jsonschema: dict[str, Any]
    def __init__(self) -> None: ...
    def validate(self, json: dict[str, Any]) -> None: ...

class Nftables:
    debug_flags: dict[str, int]
    output_flags: dict[str, int]

    validator: SchemaValidator | None

    # Ctypes methods, I won't bother typing those, we use the wrapper defined on the
    # class, see below...
    nft_ctx_new: Incomplete
    nft_ctx_output_get_flags: Incomplete
    nft_ctx_output_set_flags: Incomplete
    nft_ctx_output_get_debug: Incomplete
    nft_ctx_output_set_debug: Incomplete
    nft_ctx_buffer_output: Incomplete
    nft_ctx_get_output_buffer: Incomplete
    nft_ctx_buffer_error: Incomplete
    nft_ctx_get_error_buffer: Incomplete
    nft_run_cmd_from_buffer: Incomplete
    nft_run_cmd_from_filename: Incomplete
    nft_ctx_add_include_path: Incomplete
    nft_ctx_clear_include_paths: Incomplete
    nft_ctx_get_dry_run: Incomplete
    nft_ctx_set_dry_run: Incomplete
    nft_ctx_add_var: Incomplete
    nft_ctx_clear_vars: Incomplete
    nft_ctx_free: Incomplete

    def __init__(self, sofile: str = "libnftables.so.1") -> None: ...
    def __del__(self) -> None: ...
    def get_reversedns_output(self) -> bool: ...
    def set_reversedns_output(self, val: bool) -> bool: ...
    def get_service_output(self) -> bool: ...
    def set_service_output(self, val: bool) -> bool: ...
    def get_stateless_output(self) -> bool: ...
    def set_stateless_output(self, val: bool) -> bool: ...
    def get_handle_output(self) -> bool: ...
    def set_handle_output(self, val: bool) -> bool: ...
    def get_json_output(self) -> bool: ...
    def set_json_output(self, val: bool) -> bool: ...
    def get_echo_output(self) -> bool: ...
    def set_echo_output(self, val: bool) -> bool: ...
    def get_guid_output(self) -> bool: ...
    def set_guid_output(self, val: bool) -> bool: ...
    def get_numeric_proto_output(self) -> bool: ...
    def set_numeric_proto_output(self, val: bool) -> bool: ...
    def get_numeric_prio_output(self) -> bool: ...
    def set_numeric_prio_output(self, val: bool) -> bool: ...
    def get_numeric_symbol_output(self) -> bool: ...
    def set_numeric_symbol_output(self, val: bool) -> bool: ...
    def get_numeric_time_output(self) -> bool: ...
    def set_numeric_time_output(self, val: bool) -> bool: ...
    def get_terse_output(self) -> bool: ...
    def set_terse_output(self, val: bool) -> bool: ...
    def get_debug(self) -> list[str]: ...
    def set_debug(self, values: Iterable[int | str] | int | str) -> list[str]: ...
    def cmd(self, cmdline: str | bytes) -> tuple[int, str, str]: ...
    def json_cmd(
        self, json_root: dict[str, Any]
    ) -> tuple[int, dict[str, Any], str]: ...
    def json_validate(self, json_root: dict[str, Any]) -> bool: ...
    def cmd_from_file(self, filename: str | bytes) -> tuple[int, str, str]: ...
    def add_include_path(self, filename: str | bytes) -> bool: ...
    def clear_include_paths(self) -> None: ...
    def get_dry_run(self) -> bool: ...
    def set_dry_run(self, onoff: bool) -> bool: ...
    def add_var(self, var: str | bytes) -> bool: ...
    def clear_vars(self) -> None: ...
