services:
  router1:
    # ctftest image has additinal dependencies for debugging
    image: ci.attacking-lab.com/ctf-route/ctftest
    command: python -m ctfroute --debug --debug-server 10.43.2.1:42424 ./ctfroute.yml
    volumes:
      - ../ctfroute/ctfroute:/opt/ctfroute/ctfroute/ctfroute
      - ../ctfroute-k8s/ctfroute_k8s:/opt/ctfroute/ctfroute-k8s/ctfroute_k8s
      - ~/.kube/config:/root/.kube/config
      - ./kubernetes.ctfroute.yml:/opt/ctfroute/ctfroute.yml

  router2:
    volumes:
      - ~/.kube/config:/root/.kube/config
      - ./kubernetes.ctfroute.yml:/opt/ctfroute/ctfroute.yml

  router3:
    volumes:
      - ~/.kube/config:/root/.kube/config
      - ./kubernetes.ctfroute.yml:/opt/ctfroute/ctfroute.yml

  router-infra:
    volumes:
      - ~/.kube/config:/root/.kube/config
      - ./kubernetes.ctfroute.yml:/opt/ctfroute/ctfroute.yml

  vulnbox1:
    command: -c "wg-quick up client1 && ctftest-agent --debug --debug-server 10.43.2.1:42425 & iperf3 -s -p 1999"
    volumes:
      - ../ctfroute/ctfroute:/opt/ctfroute/ctfroute/ctfroute
      - ../ctftest/ctftest:/opt/ctfroute/ctftest/ctftest
      - ./kubernetes.ctfroute.yml:/opt/ctfroute/ctfroute.yml

  vulnbox2:
    volumes:
      - ../ctfroute/ctfroute:/opt/ctfroute/ctfroute/ctfroute
      - ./kubernetes.ctfroute.yml:/opt/ctfroute/ctfroute.yml

  vulnbox3:
    volumes:
      - ../ctfroute/ctfroute:/opt/ctfroute/ctfroute/ctfroute
      - ./kubernetes.ctfroute.yml:/opt/ctfroute/ctfroute.yml

  vulnbox4:
    volumes:
      - ../ctfroute/ctfroute:/opt/ctfroute/ctfroute/ctfroute
      - ./kubernetes.ctfroute.yml:/opt/ctfroute/ctfroute.yml

  api:
    profiles:
      - donotstart
