[Interface]
PrivateKey = INNPijh5wkwrBNVM3lYwIBlrOfJ9wLahtr1h91/ZV3g=
Address = 10.32.2.2/16
MTU = 1420

[Peer]
PublicKey = 04imYC7Ed2zEKZiiED5PT7mTkf2gMJXF9HO2hdcvp2U=
Endpoint = 10.43.2.12:50002
AllowedIPs = 10.32.0.0/16
PersistentKeepalive = 1