[Interface]
PrivateKey = wLmP7si4Ytzq7AF+zwx5aUt7libdb1Cp5/TzuNOsmGE=
Address = 10.32.1.2/16
MTU = 1420

[Peer]
PublicKey = 04imYC7Ed2zEKZiiED5PT7mTkf2gMJXF9HO2hdcvp2U=
Endpoint = 10.43.2.11:50001
AllowedIPs = 10.32.0.0/16
PersistentKeepalive = 1