[Interface]
PrivateKey = yDrrbuOExuLz3je/XWlLD1+4od6iTonnI2GbGxjAx0g=
Address = 10.32.4.2/16
MTU = 1420

[Peer]
PublicKey = QBVE5EJD0nMgh1MJfD4ZUJ+rXB8+AifjadRLoTCgBko=
Endpoint = 10.43.2.13:50004
AllowedIPs = 10.32.0.0/16
PersistentKeepalive = 1
