[Interface]
PrivateKey = sI3sgMDc0wdMY2MYoSzYCzlO/J27JjQMowqXA1aKS24=
Address = 10.32.3.2/16
MTU = 1420

[Peer]
PublicKey = 04imYC7Ed2zEKZiiED5PT7mTkf2gMJXF9HO2hdcvp2U=
Endpoint = 10.43.2.13:50003
AllowedIPs = 10.32.0.0/16
PersistentKeepalive = 1