[Interface]
PrivateKey = CLc08nydfKj4H5ZD1ejCFwF/voodPbZJ0nwW/p1sxHc=
Address = 10.32.1.3/16
MTU = 1420

[Peer]
PublicKey = 04imYC7Ed2zEKZiiED5PT7mTkf2gMJXF9HO2hdcvp2U=
Endpoint = 10.43.2.11:50001
AllowedIPs = 10.32.0.0/16
PersistentKeepalive = 1