# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ctftest.agent.ctftest_pb2 as ctftest__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ctftest_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CtfTestAgentStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ping = channel.unary_unary(
                '/ctftest.CtfTestAgent/ping',
                request_serializer=ctftest__pb2.PingRequest.SerializeToString,
                response_deserializer=ctftest__pb2.PingResponse.FromString,
                _registered_method=True)
        self.listen = channel.unary_stream(
                '/ctftest.CtfTestAgent/listen',
                request_serializer=ctftest__pb2.ListenRequest.SerializeToString,
                response_deserializer=ctftest__pb2.ListenResponse.FromString,
                _registered_method=True)
        self.sniff = channel.unary_unary(
                '/ctftest.CtfTestAgent/sniff',
                request_serializer=ctftest__pb2.StartSniffRequest.SerializeToString,
                response_deserializer=ctftest__pb2.StartSniffResponse.FromString,
                _registered_method=True)
        self.stopSniff = channel.unary_unary(
                '/ctftest.CtfTestAgent/stopSniff',
                request_serializer=ctftest__pb2.StopSniffRequest.SerializeToString,
                response_deserializer=ctftest__pb2.StopSniffResponse.FromString,
                _registered_method=True)
        self.getSniffRecording = channel.unary_unary(
                '/ctftest.CtfTestAgent/getSniffRecording',
                request_serializer=ctftest__pb2.SniffRecordingRequest.SerializeToString,
                response_deserializer=ctftest__pb2.SniffRecordingResponse.FromString,
                _registered_method=True)
        self.send = channel.unary_unary(
                '/ctftest.CtfTestAgent/send',
                request_serializer=ctftest__pb2.SendRequest.SerializeToString,
                response_deserializer=ctftest__pb2.SendResponse.FromString,
                _registered_method=True)
        self.iperf = channel.unary_stream(
                '/ctftest.CtfTestAgent/iperf',
                request_serializer=ctftest__pb2.IperfRequest.SerializeToString,
                response_deserializer=ctftest__pb2.IperfResponse.FromString,
                _registered_method=True)
        self.httpGet = channel.unary_unary(
                '/ctftest.CtfTestAgent/httpGet',
                request_serializer=ctftest__pb2.HttpGet.SerializeToString,
                response_deserializer=ctftest__pb2.HttpResponse.FromString,
                _registered_method=True)


class CtfTestAgentServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listen(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sniff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def stopSniff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getSniffRecording(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def send(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def iperf(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def httpGet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CtfTestAgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ping': grpc.unary_unary_rpc_method_handler(
                    servicer.ping,
                    request_deserializer=ctftest__pb2.PingRequest.FromString,
                    response_serializer=ctftest__pb2.PingResponse.SerializeToString,
            ),
            'listen': grpc.unary_stream_rpc_method_handler(
                    servicer.listen,
                    request_deserializer=ctftest__pb2.ListenRequest.FromString,
                    response_serializer=ctftest__pb2.ListenResponse.SerializeToString,
            ),
            'sniff': grpc.unary_unary_rpc_method_handler(
                    servicer.sniff,
                    request_deserializer=ctftest__pb2.StartSniffRequest.FromString,
                    response_serializer=ctftest__pb2.StartSniffResponse.SerializeToString,
            ),
            'stopSniff': grpc.unary_unary_rpc_method_handler(
                    servicer.stopSniff,
                    request_deserializer=ctftest__pb2.StopSniffRequest.FromString,
                    response_serializer=ctftest__pb2.StopSniffResponse.SerializeToString,
            ),
            'getSniffRecording': grpc.unary_unary_rpc_method_handler(
                    servicer.getSniffRecording,
                    request_deserializer=ctftest__pb2.SniffRecordingRequest.FromString,
                    response_serializer=ctftest__pb2.SniffRecordingResponse.SerializeToString,
            ),
            'send': grpc.unary_unary_rpc_method_handler(
                    servicer.send,
                    request_deserializer=ctftest__pb2.SendRequest.FromString,
                    response_serializer=ctftest__pb2.SendResponse.SerializeToString,
            ),
            'iperf': grpc.unary_stream_rpc_method_handler(
                    servicer.iperf,
                    request_deserializer=ctftest__pb2.IperfRequest.FromString,
                    response_serializer=ctftest__pb2.IperfResponse.SerializeToString,
            ),
            'httpGet': grpc.unary_unary_rpc_method_handler(
                    servicer.httpGet,
                    request_deserializer=ctftest__pb2.HttpGet.FromString,
                    response_serializer=ctftest__pb2.HttpResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ctftest.CtfTestAgent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ctftest.CtfTestAgent', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CtfTestAgent(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ctftest.CtfTestAgent/ping',
            ctftest__pb2.PingRequest.SerializeToString,
            ctftest__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def listen(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ctftest.CtfTestAgent/listen',
            ctftest__pb2.ListenRequest.SerializeToString,
            ctftest__pb2.ListenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def sniff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ctftest.CtfTestAgent/sniff',
            ctftest__pb2.StartSniffRequest.SerializeToString,
            ctftest__pb2.StartSniffResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def stopSniff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ctftest.CtfTestAgent/stopSniff',
            ctftest__pb2.StopSniffRequest.SerializeToString,
            ctftest__pb2.StopSniffResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getSniffRecording(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ctftest.CtfTestAgent/getSniffRecording',
            ctftest__pb2.SniffRecordingRequest.SerializeToString,
            ctftest__pb2.SniffRecordingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def send(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ctftest.CtfTestAgent/send',
            ctftest__pb2.SendRequest.SerializeToString,
            ctftest__pb2.SendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def iperf(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ctftest.CtfTestAgent/iperf',
            ctftest__pb2.IperfRequest.SerializeToString,
            ctftest__pb2.IperfResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def httpGet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ctftest.CtfTestAgent/httpGet',
            ctftest__pb2.HttpGet.SerializeToString,
            ctftest__pb2.HttpResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
