{{/*
Lookup existing secret data (if available), otherwise generate fresh passwords.
Also computes REDIS_URL which contains the REDIS_PASSWORD.
*/}}
{{- define "gen.secret" -}}
{{- $secret := lookup "v1" "Secret" .Release.Namespace (print "platform-secrets") -}}
{{- if $secret -}}
REDIS_PASSWORD: {{ $secret.data.REDIS_PASSWORD | quote }}
DJANGO_SECRET_KEY: {{ $secret.data.DJANGO_SECRET_KEY | quote }}
REDIS_URL: {{ print "redis://default:" ($secret.data.REDIS_PASSWORD | b64dec) "@platform-redis:6379/0" | b64enc }}
{{- else -}}
{{- $redis_pass := randAlphaNum 16 }}
REDIS_PASSWORD: {{ $redis_pass | b64enc }}
DJANGO_SECRET_KEY: {{ randAlphaNum 32 | b64enc }}
REDIS_URL: {{ print "redis://default:" $redis_pass "@platform-redis:6379/0" | b64enc }}
{{- end -}}
{{- end -}}

---
apiVersion: v1
kind: Secret
metadata:
  name: "platform-secrets"
  labels:
    {{ include "platform.labels" . | nindent 4}}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data: {{- ( include "gen.secret" . ) | nindent 2 -}}
