include_if_exists = '/var/lib/postgresql/data/postgresql.conf' # Include all the defaults

hba_file = '/etc/postgres/pg_hba.conf'
max_connections = 1024
max_locks_per_transaction = 1024
reserved_connections = 64
shared_buffers = 1GB
ssl = on
ssl_cert_file = '/state/db/tls/tls.crt'
ssl_key_file = '/state/db/tls/tls.key'

shared_preload_libraries = 'pg_cron'
cron.database_name = 'firewall'
cron.log_run = off
cron.use_background_workers = on

include_if_exists = '/etc/postgres/overrides.conf'
