apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: grafana-oauth
  namespace: kube-prometheus
spec:
  targetNamespace: kube-prometheus
  repo: https://oauth2-proxy.github.io/manifests
  chart: oauth2-proxy
  version: 7.12.18
  valuesContent: |-
    config:
      existingSecret: oauth2-proxy-grafana
      configFile: |
        upstreams = [
          "http://cluster-grafana-service.kube-prometheus.svc.cluster.local:3000"
        ]
        provider="keycloak-oidc" 
        oidc_issuer_url="https://auth.attacking-lab.com/realms/master"
        redirect_url="https://grafana-cluster.gartenverein-tackenberg.de/oauth2/callback"
        allowed_groups="admin"
        code_challenge_method="S256"
        email_domains="*"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-via-oauth2-proxy
  namespace: kube-prometheus
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - grafana-cluster.gartenverein-tackenberg.de
  rules:
    - host: grafana-cluster.gartenverein-tackenberg.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana-oauth-oauth2-proxy
                port:
                  name: http
