- name: "ECSC-Checker"
  hosts: all
  become: true
  become_method: ansible.builtin.sudo
  vars_files:
    - "static.yml"
    - "secrets.yml"

  roles:
    # - role: vulnbox_checkers_repo
    #   vulnbox_checkers_repo_url: "{{ ecsc_vulnbox_meta_repo_url }}"
    #   vulnbox_checkers_repo_env_secrets: "{{ checker_env_secrets }}"
    #   vulnbox_checkers_repo_registry:
    #     server: "{{ image_registry_token.server }}"
    #     username: "{{ image_registry_token.username }}"
    #     password: "{{ image_registry_token.password }}"

    - role: vulnbox_artifact_checkers
      vulnbox_artifact_checkers_repo_url: "{{ ecsc_vulnbox_meta_repo_url }}"
      vulnbox_artifact_checkers_env_secrets: "{{ checker_env_secrets }}"
      vulnbox_artifact_checkers_registry:
        server: "{{ artifact_registry_token.server }}"
        username: "{{ artifact_registry_token.username }}"
        password: "{{ artifact_registry_token.password }}"
