{
 "title": "Cluster overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Up Timeline",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg by(role)(label_replace(up{job=~\".*node-exporter.*\", job!~\".*vulnbox.*\"}, \"role\", \"$1\", \"node\", \"[^-]+-(.*)-\\\\d+\"))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum by(role)(label_replace(up{job=~\".*node-exporter.*\", job!~\".*vulnbox.*\"}, \"role\", \"$1\", \"node\", \"[^-]+-(.*)-\\\\d+\"))",
     "legendFormat": "__auto"
    },
    {
     "expr": "count by(role)(label_replace(up{job=~\".*node-exporter.*\", job!~\".*vulnbox.*\"}, \"role\", \"$1\", \"node\", \"[^-]+-(.*)-\\\\d+\"))",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by(role)(label_replace(up{job=~\".*node-exporter.*\", job!~\".*vulnbox.*\"}, \"role\", \"$1\", \"node\", \"[^-]+-(.*)-\\\\d+\"))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 27, "w": 16, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100 - (avg by(node) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)"
    },
    {
     "expr": "100 * (1 - ((node_memory_MemAvailable_bytes or node_memory_Buffers_bytes + node_memory_Cached_bytes + node_memory_MemFree_bytes) / node_memory_MemTotal_bytes))"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\"})"
    },
    {
     "expr": "sum by(node) (rate(node_network_receive_bytes_total{device=\"ext\"}[5m]))"
    },
    {
     "expr": "sum by(node) (rate(node_network_transmit_bytes_total{device=\"ext\"}[5m]))"
    },
    {
     "expr": "max by(node) (kubelet_active_pods{node=~\".+\"})"
    }
   ]
  },
  {
   "title": "/mnt/pcaps usage (percent)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/mnt/pcaps\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/mnt/pcaps\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Amount of pcap mounts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "count(node_filesystem_avail_bytes{mountpoint=\"/mnt/pcaps\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}