{
 "title": "Services",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Service Availability (up + recovering + flagmissing)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"start\" AS \"time\", services.\"name\", \"value\"\nFROM (\n\tSELECT tick, service_id, COUNT(*) AS \"value\"\n\tFROM checker_results \n\tWHERE tick >= 0 AND status IN ('SUCCESS', 'FLAGMISSING', 'RECOVERING')\n\tGROUP BY tick, service_id, service_id\n\tORDER BY tick ASC \n) AS checker_results\nLEFT JOIN services ON service_id = services.id\nJOIN ticks ON checker_results.tick = ticks.tick"
    }
   ]
  },
  {
   "title": "Service Health per Tick (sum)",
   "type": "trend",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT tick, count(*) AS \"successful checker runs\"\nFROM checker_results\nWHERE status IN ('SUCCESS', 'FLAGMISSING', 'RECOVERING') AND tick > 0\nGROUP BY tick\nORDER BY tick ASC"
    }
   ]
  },
  {
   "title": "Average Checker Runtimes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT \"start\" AS \"time\", services.\"name\", \"value\"\nFROM (\n\tSELECT tick, service_id, AVG(\"time\") AS \"value\"\n\tFROM checker_results \n\tWHERE tick >= 0\n\tGROUP BY tick, service_id\n\tORDER BY tick ASC \n) AS checker_results\nLEFT JOIN services ON service_id = services.id\nJOIN ticks ON checker_results.tick = ticks.tick"
    }
   ]
  },
  {
   "title": "Submitted Flags (by service + flag store)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "rawSql": "SELECT ticks.\"start\" AS \"time\", CONCAT(services.name, ' (', payload, ')') AS \"name\", \"value\"\nFROM (\n\tSELECT tick_submitted, service_id, payload, COUNT(*) AS \"value\" \n\tFROM submitted_flags \n\tGROUP BY tick_submitted, service_id, payload\n\tORDER BY tick_submitted\n)\nLEFT JOIN services ON service_id = services.id\nJOIN ticks ON tick = tick_submitted;"
    }
   ]
  },
  {
   "title": "Attackers (by service + flag store)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "rawSql": "SELECT ticks.\"start\" AS \"time\", CONCAT(services.name, ' (', payload, ')') AS \"name\", \"value\"\nFROM (\n\tSELECT tick_submitted, service_id, payload, COUNT(DISTINCT submitted_by) AS \"value\" \n\tFROM submitted_flags \n\tGROUP BY tick_submitted, service_id, payload\n\tORDER BY tick_submitted\n)\nLEFT JOIN services ON service_id = services.id\nJOIN ticks ON tick = tick_submitted;"
    }
   ]
  },
  {
   "title": "Victims (by service + flag store)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "rawSql": "SELECT ticks.\"start\" AS \"time\", CONCAT(services.name, ' (', payload, ')') AS \"name\", \"value\"\nFROM (\n\tSELECT tick_submitted, service_id, payload, COUNT(DISTINCT team_id) AS \"value\" \n\tFROM submitted_flags \n\tGROUP BY tick_submitted, service_id, payload\n\tORDER BY tick_submitted\n)\nLEFT JOIN services ON service_id = services.id\nJOIN ticks ON tick = tick_submitted;"
    }
   ]
  },
  {
   "title": "Submitted Flags (by service)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "rawSql": "SELECT ticks.\"start\" AS \"time\", services.name AS \"name\", \"value\"\nFROM (\n\tSELECT tick_submitted, service_id, COUNT(*) AS \"value\" \n\tFROM submitted_flags \n\tGROUP BY tick_submitted, service_id\n\tORDER BY tick_submitted\n)\nLEFT JOIN services ON service_id = services.id\nJOIN ticks ON tick = tick_submitted;"
    }
   ]
  }
 ]
}