{
 "title": "Traffic Connections (psql)",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Network Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  sum(src_bytes+dst_bytes) / ($__interval_ms / 1000) AS \"total traffic\",\n  sum(src_packets+dst_packets) / ($__interval_ms / 1000) AS \"total packets\"\nFROM vpn_traffic\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Connection Timing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  sum(connection_times) / GREATEST(1, sum(connection_count)) AS \"average connection time\",\n  sum(connection_count) / ($__interval_ms / 1000) AS \"connection count\"\nFROM vpn_traffic\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Traffic - Top Teams",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  src AS \"src team\",\n  (sum(src_bytes) + sum(dst_bytes)) AS \"total traffic\"\nFROM vpn_traffic\nGROUP BY src\nORDER BY \"total traffic\" DESC"
    }
   ]
  },
  {
   "title": "Bandwidth per Team",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  src,\n  sum(src_bytes + dst_bytes) / ($__interval_ms / 1000) AS \"traffic\"\nFROM vpn_traffic\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY \"time\", src\nORDER BY \"time\" ASC"
    }
   ]
  },
  {
   "title": "Traffic per port (within timerange)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  max(time) AS \"time\",\n  CONCAT(proto, ' ', CASE WHEN port = -1 THEN '(other)' ELSE CONCAT(':', port) END) AS \"title\",\n  sum(src_bytes + dst_bytes) AS \"bytes\"\nFROM vpn_traffic\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY proto, port\nORDER BY time, proto, port"
    }
   ]
  },
  {
   "title": "Open Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  sum(open_connections) / count(DISTINCT \"time\") AS \"open connections\"\nFROM vpn_traffic\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY \"time\"\nORDER BY 1"
    }
   ]
  },
  {
   "title": "NOP Team Ping",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroupAlias(time, $__interval), \n  AVG(average_response_ms) AS rtt,\n  AVG(percent_packet_loss) AS \"packet loss\"\nFROM ping \nWHERE $__timeFilter(time) AND url = '10.42.1.2'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  }
 ]
}