{
 "title": "Service",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": "SELECT CONCAT(id, ' ', name) AS label FROM services\nORDER BY id"
   },
   {
    "name": "payload",
    "query": "SELECT generate_series(0, num_payloads - 1) FROM services WHERE id = $service"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Service Checker Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT \"start\" AS \"time\", \n  CASE WHEN status = 'SUCCESS' THEN ' SUCCESS' ELSE status END AS \"name\", \n  \"value\"\nFROM (\n\tSELECT tick, status, COUNT(*) AS \"value\"\n\tFROM checker_results \n\tWHERE service_id = $service AND tick >= 0\n\tGROUP BY tick, status\n\tORDER BY tick ASC\n) AS checker_results\nJOIN ticks ON checker_results.tick = ticks.tick"
    }
   ]
  },
  {
   "title": "Checker RuntIme",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT \"start\" AS \"time\", \"value\" AS \"avg. checker time\"\nFROM (\n\tSELECT tick, AVG(time) AS \"value\"\n\tFROM checker_results \n\tWHERE service_id = $service AND tick >= 0\n\tGROUP BY tick\n\tORDER BY tick ASC\n) AS checker_results\nJOIN ticks ON checker_results.tick = ticks.tick"
    },
    {
     "rawSql": "SELECT \"start\" AS \"time\", \"value\" AS \"avg. successful checker time\"\nFROM (\n\tSELECT tick, AVG(time) AS \"value\"\n\tFROM checker_results \n\tWHERE service_id = $service AND tick >= 0 AND status = 'SUCCESS'\n\tGROUP BY tick\n\tORDER BY tick ASC\n) AS checker_results\nJOIN ticks ON checker_results.tick = ticks.tick"
    },
    {
     "rawSql": "SELECT \"start\" AS \"time\", \"value\" AS \"max. checker time\"\nFROM (\n\tSELECT tick, MAX(time) AS \"value\"\n\tFROM checker_results \n\tWHERE service_id = $service AND tick >= 0\n\tGROUP BY tick\n\tORDER BY tick ASC\n) AS checker_results\nJOIN ticks ON checker_results.tick = ticks.tick"
    },
    {
     "rawSql": "SELECT start AS \"time\", (SELECT checker_timeout FROM services WHERE id=$service) AS \"timeout limit\"\nFROM ticks\n"
    }
   ]
  },
  {
   "title": "Attackers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT ticks.\"start\" AS \"time\", CONCAT('flagstore ', payload) AS \"name\", \"value\"\nFROM (\n\tSELECT tick_submitted, service_id, payload, COUNT(DISTINCT submitted_by) AS \"value\" \n\tFROM submitted_flags \n\tWHERE service_id = $service \n\tGROUP BY tick_submitted, service_id, payload\n\tORDER BY tick_submitted\n)\nJOIN ticks ON tick = tick_submitted;"
    }
   ]
  },
  {
   "title": "Victims",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT ticks.\"start\" AS \"time\", CONCAT('flagstore ', payload) AS \"name\", \"value\"\nFROM (\n\tSELECT tick_submitted, service_id, payload, COUNT(DISTINCT team_id) AS \"value\" \n\tFROM submitted_flags \n\tWHERE service_id = $service \n\tGROUP BY tick_submitted, service_id, payload\n\tORDER BY tick_submitted\n)\nJOIN ticks ON tick = tick_submitted;"
    }
   ]
  },
  { "title": "Flagstore $payload", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }, "repeat": "payload" },
  {
   "title": "# Victims by Attacker (Flagstore $payload)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT ticks.\"start\" AS \"time\", CONCAT('#', teams.id, ' ', teams.name) AS \"name\", \"value\"\nFROM (\n\tSELECT tick_submitted, submitted_by, COUNT(DISTINCT team_id) AS \"value\" \n\tFROM submitted_flags \n\tWHERE service_id = $service AND payload = $payload\n\tGROUP BY tick_submitted, submitted_by, service_id\n\tORDER BY tick_submitted\n)\nJOIN ticks ON tick = tick_submitted\nJOIN teams ON submitted_by = teams.id"
    }
   ]
  },
  {
   "title": "Exploiters for $service, Flagstore $payload",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT CONCAT('#', submitted_by, ' ', teams.name) AS \"Team\", \n  MIN(ts) AS \"first exploited\", \n  CASE WHEN MIN(ts) FILTER (WHERE victims >= 10) IS NOT NULL\n    THEN CONCAT(age(date_trunc('second', MIN(ts) FILTER (WHERE victims >= 10)), date_trunc('second', MIN(ts))), ' later')\n    ELSE 'never'\n  END AS \"... >= 10 teams\", \n  MAX(victims) AS \"max. victims\", \n  SUM(flags) AS \"total flags\"\nFROM (\n\tSELECT tick_submitted, submitted_by, MIN(ts) AS ts, COUNT(*) AS flags, COUNT(DISTINCT team_id) AS \"victims\" \n\tFROM submitted_flags \n\tWHERE service_id = $service AND payload = $payload\n\tGROUP BY tick_submitted, submitted_by\n)\nJOIN teams ON submitted_by = teams.id\nGROUP BY submitted_by, teams.name\nORDER BY MIN(ts)"
    }
   ]
  }
 ]
}