{
 "title": "Flag Submitter",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "team",
    "query": "SELECT DISTINCT team FROM submitter_flags ORDER BY team;"
   }
  ]
 },
 "panels": [
  {
   "title": "Submitted Flags",
   "type": "timeseries",
   "description": "Submitted flags per minute",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroupAlias(time, $__interval), \n  AVG(count_new)*4 AS \"new\", \n  AVG(count_old)*4 AS \"old\", \n  AVG(count_expired)*4 AS \"expired\", \n  AVG(count_invalid)*4 AS \"invalid\", \n  AVG(count_nop)*4 AS \"nop\", \n  AVG(count_own)*4 AS \"own\"\nFROM submitter_flags \nWHERE $__timeFilter(time) AND team IN ($team)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total Flags Incoming",
   "type": "timeseries",
   "description": "How many flags we receive per second",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroupAlias(time, $__interval), \n  (SUM(count_new) + SUM(count_old) + SUM(count_expired) + SUM(count_invalid) + SUM(count_own) + SUM(count_nop)) * 1000 / $__interval_ms AS flags\nFROM submitter_flags\nWHERE $__timeFilter(time) AND team IN ($team)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Flag Submitter Connections",
   "type": "timeseries",
   "description": "All connections / fd's, ignoring the \"team\" filter",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroupAlias(time, $__interval), \n  AVG(open_connections) AS \"open connections\",\n  AVG(total_connections) / 15 AS \"connections per second\",\n  AVG(fd_count) AS \"fd count\",\n  AVG(fd_max) AS \"fd limit\"\nFROM submitter_connections \nWHERE $__timeFilter(time)\nGROUP BY 1\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Flag Submitter Cache Performance",
   "type": "timeseries",
   "description": "Submission server cache performance for the whole instance, not affected by team filter",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroupAlias(time, $__interval), \n  AVG(cache_hits) AS \"cache hits\",\n  AVG(cache_misses) AS \"cache misses\",\n  AVG(cache_fails) AS \"cache fails\"\nFROM submitter_cache \nWHERE $__timeFilter(time)\nGROUP BY 1\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Submitted Flags",
   "type": "timeseries",
   "description": "Submitted flags per minute",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroupAlias(time, $__interval), \n  AVG(count_new)*4 AS \"new\", \n  AVG(count_old)*4 AS \"old\", \n  AVG(count_expired)*4 AS \"expired\", \n  AVG(count_invalid)*4 AS \"invalid\", \n  AVG(count_nop)*4 AS \"nop\", \n  AVG(count_own)*4 AS \"own\"\nFROM submitter_flags \nWHERE $__timeFilter(time) AND team IN ($team)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  }
 ]
}