{
 "title": "Router System Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "routerpattern", "label": "Router Pattern", "query": ".*-router-.*" },
   {
    "name": "team",
    "label": "Team",
    "query": {
     "query": "label_values(node_network_transmit_bytes_total{device=~\"tt-.*\"},device)"
    }
   },
   { "name": "mininterval", "label": "Min Interval", "query": "10s,15s,20s,5s" }
  ]
 },
 "panels": [
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Traffic to teams",
   "type": "heatmap",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "label_replace(max by (device) (rate(node_network_transmit_bytes_total{device=~\"tt-.*\", device=~\"tt-$team\"}[$__rate_interval])) * 8, \"team\", \"$1\", \"device\", \"tt-(.*)\")",
     "legendFormat": "{{team}}"
    }
   ]
  },
  {
   "title": "Traffic from teams",
   "type": "heatmap",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "label_replace(max by (device) (rate(node_network_receive_bytes_total{device=~\"tt-.*\", device=~\"tt-$team\"}[$__rate_interval])) * 8, \"team\", \"$1\", \"device\", \"tt-(.*)\")",
     "legendFormat": "{{team}}"
    }
   ]
  },
  {
   "title": "Traffic to teams",
   "type": "heatmap",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "label_replace(max by (device) (rate(node_network_transmit_bytes_total{device=~\"tt-.*\", device=~\"tt-$team\"}[$__rate_interval])) * 8, \"team\", \"$1\", \"device\", \"tt-(.*)\")",
     "legendFormat": "{{team}}"
    }
   ]
  },
  {
   "title": "Traffic from the world",
   "type": "heatmap",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "label_replace(max by (node) (rate(node_network_receive_bytes_total{device=~\"ext\", node=~\".*router.*\"}[$__rate_interval])) * 8, \"router\", \"$1\", \"node\", \".*-router-(.*)\")",
     "legendFormat": "{{router}}"
    }
   ]
  },
  { "title": "Packets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Packets to teams",
   "type": "heatmap",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "label_replace(max by (device) (rate(node_network_transmit_packets_total{device=~\"tt-.*\", device=~\"tt-$team\"}[$__rate_interval])), \"team\", \"$1\", \"device\", \"tt-(.*)\")",
     "legendFormat": "{{team}}"
    }
   ]
  },
  {
   "title": "Packets from teams",
   "type": "heatmap",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "label_replace(max by (device) (rate(node_network_receive_packets_total{device=~\"tt-.*\", device=~\"tt-$team\"}[$__rate_interval])), \"team\", \"$1\", \"device\", \"tt-(.*)\")",
     "legendFormat": "{{team}}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Router CPU loads",
   "type": "heatmap",
   "gridPos": { "h": 23, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "100 - max by (node)(rate(node_cpu_seconds_total{mode=\"idle\", node=~\"$routerpattern\", node=~\".*-router-$team\"}[$__rate_interval]) * 100)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Router Memory loads",
   "type": "heatmap",
   "gridPos": { "h": 23, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "100 * (1 - ((node_memory_MemAvailable_bytes or node_memory_Buffers_bytes + node_memory_Cached_bytes + node_memory_MemFree_bytes) / node_memory_MemTotal_bytes{ node=~\"$routerpattern\", node=~\".*-router-$team\"}))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Conntrack Entries (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "node_nf_conntrack_entries / node_nf_conntrack_entries_limit",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Conntrack Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "targets": [
    {
     "expr": "node_nf_conntrack_stat_insert_failed",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}