"""
Django settings for saarctf project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import json
import os
from datetime import UTC, datetime, timezone
from pathlib import Path
from typing import cast

from django.contrib import messages
from dotenv import load_dotenv

from mainpage.vmtemplate import VmTemplate

load_dotenv()

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = Path(__file__).parent.parent
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "k*(#k(ec$&e7l8q3xwyv--49mtx3w#@((4pkohxezutn&4i!^q"

PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
    "django.contrib.auth.hashers.ScryptPasswordHasher",
    # PKDF2 is expensive, this is used to make creating large amounts of test accounts
    # feasible
    "django.contrib.auth.hashers.MD5PasswordHasher",
]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ENVIRONMENT = "dev"

HOST_NAME = os.environ.get("HOST_NAME", "")
ALLOWED_HOSTS = [HOST_NAME] if HOST_NAME else ["*"]
CSRF_TRUSTED_ORIGINS = (
    [f"http://{HOST_NAME}", f"https://{HOST_NAME}"]
    if HOST_NAME
    else [
        "http://localhost:5173",
        "http://localhost:8080",
        "http://127.0.0.1:5173",
        "http://127.0.0.1:8080",
    ]
)

USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "/"
LOGINAS_REDIRECT_URL = "/team"
LOGINAS_LOGOUT_REDIRECT_URL = "/team_list"
PASSWORD_RESET_TIMEOUT_DAYS = 7

# we use django_allauth for admin authentication against Keycloak.
if (
    "OAUTH_CLIENT_ID" in os.environ
    and "OAUTH_SECRET" in os.environ
    and "OAUTH_CONFIG_URL" in os.environ
):
    SOCIALACCOUNT_PROVIDERS = {
        "keycloak": {
            "APPS": [
                {
                    "provider_id": "keycloak",
                    "name": "Attacking-Lab Account",
                    "client_id": os.environ["OAUTH_CLIENT_ID"],
                    "secret": os.environ["OAUTH_SECRET"],
                    "settings": {
                        "server_url": os.environ["OAUTH_CONFIG_URL"],
                        "scope": [
                            "openid",
                            "profile",
                            "email",
                            "groups",
                            "roles",
                            "microprofile-jwt",
                        ],
                        "required_roles": ["admin"],
                    },
                }
            ]
        }
    }
else:
    SOCIALACCOUNT_PROVIDERS = {}
    SOCIALACCOUNT_ADAPTER = "mainpage.provider.AdminSocialAccountAdapter"
    ACCOUNT_EMAIL_VERIFICATION = "none"
    SOCIALACCOUNT_EMAIL_AUTHENTICATION = "none"
    SOCIALACCOUNT_ONLY = True


# Confirmation Mail Configuration

# Uncomment this one to test emails
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = os.getenv("EMAIL_HOST", "")
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_PORT = 587
EMAIL_DEFAULT_FROM = os.getenv("EMAIL_DEFAULT_FROM", "")

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.forms",
    "constance",
    "rest_framework",
    "loginas",
    "hcaptcha",
    "crispy_forms",
    "crispy_bootstrap4",
    "django_q",
    "allauth",
    "allauth.account",  # TODO remove?
    "allauth.socialaccount",
    "allauth.socialaccount.providers.openid_connect",
    "mainpage",
]

USE_CAPTCHA = False

CRISPY_TEMPLATE_PACK = "bootstrap4"
FORM_RENDERER = "django.forms.renderers.TemplatesSetting"
HCAPTCHA_SITEKEY = "000000000000000000000000000000000000"
HCAPTCHA_SECRET = "0xAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",  # TODO remove?
]

ROOT_URLCONF = "mainpage.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "mainpage" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "mainpage.context_processors.template_settings",
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

WSGI_APPLICATION = "mainpage.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
    }
}

if all(k in os.environ for k in ("POSTGRES_DB", "POSTGRES_USER", "POSTGRES_PASSWORD")):
    DATABASES["default"] = {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ["POSTGRES_DB"],
        "USER": os.environ["POSTGRES_USER"],
        "PASSWORD": os.environ["POSTGRES_PASSWORD"],
        "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
        "PORT": os.environ.get("POSTGRES_PORT", "5432"),
    }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Django Message Tags for Bootstrap4
MESSAGE_TAGS = {
    messages.DEBUG: "alert-info",
    messages.INFO: "alert-info",
    messages.SUCCESS: "alert-success",
    messages.WARNING: "alert-warning",
    messages.ERROR: "alert-danger",
}

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Set this to true to force using vite dev server, for vite assets
# even if a build exists
VITE_FORCE_DEV = False
VITE_BUILD = BASE_DIR / "vite_build"
VITE_MANIFEST = VITE_BUILD / "manifest.json"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL: str = "/static/"
STATICFILES_DIRS = [VITE_BUILD]
STATIC_ROOT: Path = BASE_DIR / "static_collected"
STATIC_DIR: str  # a writeable static directory (with subfolders like "/img/logos", ...)

MEDIA_SUBDOMAIN = "images"
MEDIA_ROOT = BASE_DIR / "uploads"
MEDIA_URL = "/media/"

NETWORK_INDEX = 42
CTF_INFO = {
    "submission_host": f"10.{NETWORK_INDEX}.251.2",
    "submission_port": 1337,
    "network_index": NETWORK_INDEX,
    "round_time": 60,
    "scoreboard_host": f"10.{NETWORK_INDEX}.251.2",
    "scoreboard_public": "https://scoreboard.ad.ecsc2025.pl",
    "attackinfo_url": f"http://10.{NETWORK_INDEX}.251.2:8080/api/v1/attack_info",
    "game_network": f"10.{NETWORK_INDEX}.0.0/16",
    "team_network": f"10.{NETWORK_INDEX}.<TEAM>.0/24",
    "vulnbox_ip": f"10.{NETWORK_INDEX}.<TEAM>.2",
    "router_ip": f"10.{NETWORK_INDEX}.<TEAM>.254",
    "flag_regex": r"ECSC\{[A-Za-z0-9_-]{32}\}",
    "name_brand": "ECSC 2025",
    "name_short": "Infra Demo",
    "name_long": "ECSC 2025 Infra Demo",
}

CONSTANCE_BACKEND = "constance.backends.database.DatabaseBackend"
CONSTANCE_ADDITIONAL_FIELDS = {
    dict: ["django.forms.fields.JSONField", {"widget": "django.forms.Textarea"}],
}
CONSTANCE_CONFIG = {
    "SHOW_CONFIG": (False, "Team ID is visible, VPN can be configured", bool),
    "ENABLE_SIGNUP": (False, "Teams can register", bool),
    "ENABLE_ACTIVATION": (False, "Teams can activate their account", bool),
    # Download URLs for the VM images, or None if no download is currently possible.
    "URL_ROUTER": ("", "Download URL for router VM image", str),
    "URL_TESTBOX": ("", "Download URL for testbox VM image", str),
    "URL_VULNBOX": ("", "Download URL for vulnbox VM image", str),
    "URL_CLOUD": ("", "Download URL for cloud bundle", str),
    # Defaults if not configured on the interface / peer directly
    "VPN_HOST": ("", "VPN Server Endpoint", str),
    "VPN_BASE_PORT": (32000, "VPN Server Endpoint Base Port", int),
    "VPN_GAME_NET": ("", "Game network to use for wireguard confs."),
    "VPN_DEFAULT_MANAGED": (True, "Set new interfaces to managed by default", bool),
    "VPN_MANGED_PLAYER_CONFIGS": (
        3,
        "Number of configs per player on managed vpn",
        int,
    ),
    "VPN_MANGED_TEAM_CONFIGS": (
        10,
        "Number of configs for team infra on managed vpn ",
        int,
    ),
    "SHOW_SCOREBOARD": (False, "Show link to scoreboard", bool),
    "URL_SCOREBOARD": (CTF_INFO["scoreboard_public"], "Scoreboard URL", str),
    "PLAYER_WG_COUNT": (2, "Number of wg keys to assign per player.", int),
    "ROUTER_TOKEN": ("", "Token used to authenticate requests from router", str),
    "HOSTING_TOKEN": ("", "Token used to authenticate requests from vulnhost", str),
    "HOSTING_ORGA_KEYS": ("", "Orga SSH Keys (one per line)", str),
    "HOSTING_CONFIGURABLE": (
        False,
        "Whether self- / cloud-hosting can be toggled",
        bool,
    ),
    # CTF Metadata
    "TIME_START": (datetime(2025, 9, 28, 9, 0, 0, tzinfo=UTC), "Start time", datetime),
    "TIME_NETWORK_OPEN": (
        datetime(2025, 9, 28, 10, 0, 0, tzinfo=UTC),
        "Network open time",
        datetime,
    ),
    "TIME_END": (datetime(2025, 9, 28, 17, 0, 0, tzinfo=UTC), "End time", datetime),
    "CTF_META": (CTF_INFO, "Ctf metadata, can be accessed as `ctf` in templates", dict),
}


HOSTING_VM_TEMPLATES: list[VmTemplate] = []
if path := os.getenv("HOSTING_VM_TEMPLATES"):
    for json_tpl in cast(list[dict], json.loads(Path(path).read_text())):
        HOSTING_VM_TEMPLATES.append(VmTemplate.from_dict(json_tpl))

# Generate constance settings for vm control if the control time is not hard
# coded in the template
for tmpl in HOSTING_VM_TEMPLATES:
    if tmpl.control_available_from is None or tmpl.control_available_to is None:
        CONSTANCE_CONFIG[tmpl.constance_setting_start] = (
            datetime(2000, 1, 1, tzinfo=timezone.utc),
            f'Enable control for "{tmpl.name}" on ({TIME_ZONE})',
            datetime,
        )
        CONSTANCE_CONFIG[tmpl.constance_setting_end] = (
            datetime(2100, 1, 1, tzinfo=timezone.utc),
            f'Disable control for "{tmpl.name}" on ({TIME_ZONE})',
            datetime,
        )

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "formatter": "default_formatter",
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "mainpage": {
            "handlers": ["console"],
            "propagate": False,
            "level": "DEBUG",
        },
        "django.db.backends": {
            "handlers": ["console"],
            "level": "DEBUG" if "SHOW_SQL" in os.environ else "INFO",
            "propagate": False,
        },
    },
    "formatters": {
        "default_formatter": {
            "format": "%(asctime)s | %(levelname)s | %(message)s | %(name)s | %(filename)s:%(lineno)s",
        },
    },
}

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
        "LOCATION": "/dev/shm/django_cache",
    }
}

Q_CLUSTER = {
    "name": "ctf-landing",
    "workers": 2,
    "timeout": 120,
    "retry": 121,
    "max_attempts": 2,
    "bulk": 2,
    "poll": 2.0,  # poll interval for ORM broker, in seconds
    "cache": "default",
    "scheduler": True,
    "catch_up": False,
}

# redis/cache backend if available
# for example: "redis://[[username]:[password]]@localhost:6379/0"
REDIS_URL: str | None = os.environ.get("REDIS_URL")

if REDIS_URL is not None:
    CACHES["default"] = {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": REDIS_URL,
    }

if REDIS_URL is not None:
    Q_CLUSTER["redis"] = REDIS_URL
else:
    Q_CLUSTER["orm"] = "default"
