---
- name: "Ensure no other firewalls exist"
  ansible.builtin.apt:
    state: "absent"
    autoremove: true
    name:
      - "ufw"
      - "iptables"
  when: nft_remove_iptables

- name: "Install nftables"
  ansible.builtin.apt:
    state: present
    name:
      - "nftables{{ nft_package_version | ternary('=', '') }}{{ nft_package_version | default('') }}"
