#!/usr/bin/env bash

# USAGE: service-add 'command' 'working directory' 'description' <<EOF
# additional config lines here
# EOF

set -eu

SERVICESUFFIX="${SERVICESUFFIX:-}"

CUSTOM_CONFIG=$(cat -)

OPTIONAL_CONFIG=""
if [[ $CUSTOM_CONFIG != *"CPUQuota"* ]]; then
  OPTIONAL_CONFIG="CPUQuota=50%"
fi

cat << EOF > /etc/systemd/system/$SERVICENAME$SERVICESUFFIX.service
[Unit]
Description=$3
After=network.target

[Service]
Type=simple
ExecStart=$1
WorkingDirectory=$2
User=$SERVICENAME
Group=$SERVICENAME
Environment=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
$OPTIONAL_CONFIG
$CUSTOM_CONFIG

[Install]
WantedBy=multi-user.target
EOF
systemctl enable $SERVICENAME$SERVICESUFFIX
