# Generated by Django 5.1.3 on 2024-11-22 19:14

import django.contrib.auth.models
import django.db.models.deletion
import mainpage.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interface",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public_key", models.CharField(blank=True, max_length=64, null=True)),
                ("cidr", models.CharField(max_length=19)),
                ("auto_ip_assignment", models.BooleanField(default=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("last_synced", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="KeySlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("public_key", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "private_key",
                    models.CharField(
                        blank=True, default=None, max_length=64, null=True
                    ),
                ),
                ("managed", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(blank=True, default="")),
                ("text", models.TextField()),
                ("html", models.TextField()),
                ("is_visible", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "News",
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("CP", "Captain"),
                            ("TE", "Technician"),
                            ("PL", "Player"),
                        ],
                        default="PL",
                        max_length=2,
                    ),
                ),
            ],
            options={
                "verbose_name": "Player",
                "verbose_name_plural": "Players",
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="ServiceToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("text", models.TextField()),
                ("html", models.TextField()),
                ("is_visible", models.BooleanField(default=False)),
                ("secret", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="TeamProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("affiliation", models.TextField(blank=True, null=True)),
                ("website", models.TextField(blank=True, null=True)),
                ("irc_name", models.TextField(blank=True, null=True)),
                ("team_id", models.IntegerField(default=None, null=True, unique=True)),
                ("logo", models.TextField(blank=True, default="")),
                ("ssh_keys", models.TextField(blank=True, default="")),
                ("use_cloudhosting", models.BooleanField(default=False)),
                (
                    "join_token",
                    models.CharField(
                        blank=True,
                        default=mainpage.models.get_team_join_token,
                        max_length=20,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Peer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                ("enabled", models.BooleanField(default=True)),
                ("cidr", models.CharField(max_length=19)),
                ("order", models.IntegerField(default=0)),
                ("managed", models.BooleanField(default=False)),
                (
                    "interface",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="peers",
                        to="mainpage.interface",
                    ),
                ),
                (
                    "key_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainpage.keyslot",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="keyslot",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mainpage.player",
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mainpage.teamprofile"
            ),
        ),
        migrations.AddField(
            model_name="interface",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mainpage.teamprofile"
            ),
        ),
        migrations.CreateModel(
            name="VMStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.TextField()),
                ("field", models.TextField()),
                ("old_value", models.JSONField(null=True)),
                ("new_value", models.JSONField(null=True)),
                ("message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainpage.teamprofile",
                        to_field="team_id",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.TextField()),
                ("config", models.JSONField()),
                ("status", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainpage.teamprofile",
                        to_field="team_id",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "team_id"), name="kind_team_id"
                    )
                ],
            },
        ),
    ]
