# Generated by Django 5.1.3 on 2024-11-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keyslot",
            name="public_key",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
