# Generated by Django 5.1.3 on 2024-11-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0002_alter_keyslot_public_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="peer",
            name="type",
            field=models.CharField(
                choices=[("CB", "Cloud box"), ("TE", "Testing"), ("AI", "Auto IP")],
                default=None,
                max_length=2,
                null=True,
            ),
        ),
        migrations.RunSQL("""UPDATE mainpage_peer SET "type" = 'CB' WHERE managed = TRUE""")
    ]
