# Generated by Django 5.1.3 on 2024-11-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0003_peer_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="peer",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("CB", "Cloud box"), ("TE", "Testing"), ("AI", "Auto IP")],
                default=None,
                max_length=2,
                null=True,
            ),
        ),
    ]
