# Generated by Django 5.2.6 on 2025-09-09 22:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_alter_peer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='managed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interface',
            name='vpn_host',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='interface',
            name='vpn_port',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)]),
        ),
    ]
