# Generated by Django 5.2.6 on 2025-09-26 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_interface_managed_interface_vpn_host_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyslot',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keyslots', to='mainpage.player'),
        ),
        migrations.AlterField(
            model_name='peer',
            name='key_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peers', to='mainpage.keyslot'),
        ),
    ]
