# Generated by Django 5.2.6 on 2025-09-26 23:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_alter_keyslot_owner_alter_peer_key_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='peer',
            name='vpn_host',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='peer',
            name='vpn_port',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AlterField(
            model_name='peer',
            name='type',
            field=models.CharField(blank=True, choices=[('CB', 'Cloud box'), ('TE', 'Testing'), ('AI', 'Auto IP'), ('PP', 'Prepared Pool')], default=None, max_length=2, null=True),
        ),
    ]
