# Generated by Django 5.2.6 on 2025-09-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_peer_vpn_host_peer_vpn_port_alter_peer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='peer',
            name='type',
            field=models.CharField(blank=True, choices=[('VB', 'Vulnbox'), ('EX', 'Exploiter'), ('TE', 'Testing'), ('AI', 'Auto IP'), ('PP', 'Prepared Pool')], default=None, max_length=2, null=True),
        ),
    ]
