# Generated by Django 5.2.6 on 2025-09-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_vm_metadata_alter_peer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='peer',
            name='overrides',
            field=models.JSONField(null=True),
        ),
    ]
