apiVersion: v1
kind: Service
metadata:
  name: vulnboxes
  labels:
    app: vulnboxes
    {{- include "ctfroute.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: prometheus
      port: 8999
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: vulnboxes-manual
  labels:
    app: ctfroute
    {{- include "ctfroute.labels" . | nindent 4 }}
    kubernetes.io/service-name: vulnboxes
    service.kubernetes.io/headless:
    managed-by: helm
addressType: IPv4
ports:
  - name: prometheus
    port: 8999
endpoints:
{{- range .Values.ctfroute.initialState.teams }}
  {{- if not (eq (toString .id) "orga") }}
  - addresses:
      - {{ .vulnbox }}
    hostname: vulnbox-{{ .id }}
    conditions:
      ready: true
  {{- end }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: exploiters
  labels:
    app: exploiters
    {{- include "ctfroute.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: placeholder
      port: 1
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: exploiters-manual
  labels:
    app: ctfroute
    {{- include "ctfroute.labels" . | nindent 4 }}
    kubernetes.io/service-name: exploiters
    service.kubernetes.io/headless:
    managed-by: helm
addressType: IPv4
ports:
  - name: placeholder
    port: 1
endpoints:
{{- range .Values.ctfroute.initialState.teams }}
  {{- if not (eq (toString .id) "orga") }}
  - addresses:
      - "10.{{ $.Values.networkIndex }}.{{ .id }}.3"
    hostname: exploiter-{{ .id }}
    conditions:
      ready: true
  {{- end }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: routers
  labels:
    app: ctfroute
    {{- include "ctfroute.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: ctfr-metrics
      port: 9000
      targetPort: ctfr-metrics
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: routers-manual
  labels:
    app: ctfroute
    {{- include "ctfroute.labels" . | nindent 4 }}
    kubernetes.io/service-name: routers
    service.kubernetes.io/headless:
    managed-by: helm
addressType: IPv4
ports:
  - name: ctfr-metrics
    port: 9000
endpoints:
{{- range .Values.ctfroute.initialState.routers }}
  - addresses:
      - {{ .connectivity.address }}
    hostname: {{ .id }}
    conditions:
      ready: true
{{- end }}
---
# Node-exporter is set up by the monitoring chart.
# TODO: If we could somehow merge these services, the setup would be less awkward
apiVersion: v1
kind: Service
metadata:
  name: routers-node-metrics
  labels:
    app: node-exporter
    {{- include "ctfroute.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: node-metrics
      port: 9100
      targetPort: node-metrics
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: routers-node-metrics-manual
  labels:
    app: node-exporter
    {{- include "ctfroute.labels" . | nindent 4 }}
    kubernetes.io/service-name: routers-node-metrics
    service.kubernetes.io/headless:
    managed-by: helm
addressType: IPv4
ports:
  - name: node-metrics
    port: 9100
endpoints:
{{- range .Values.ctfroute.initialState.routers }}
  - addresses:
      - {{ .connectivity.address }}
    hostname: {{ .id }}
    conditions:
      ready: true
{{- end }}
---
