[supervisord]
logfile = /dev/stdout
logfile_maxbytes = 0
loglevel = warn
nodaemon = true
pidfile = /var/run/supervisord.pid
umask = 077
user = root

[program:frontend]
command = /usr/local/bin/uv run gunicorn -c /var/www/gunicorn.conf.py app:app
directory = /var/www/
autorestart = true
stdout_logfile = /dev/stdout
stderr_logfile = /dev/stderr
stdout_logfile_maxbytes = 0
stderr_logfile_maxbytes = 0

[program:agent]
command = /bin/agent
user = snmp
environment = MIBDIRS="+/usr/share/mib",MIBS="/usr/share/mib/ECSC2025-ATKLAB-FIREWALL-MIB.mib"
autorestart = true
stdout_logfile = /dev/stdout
stderr_logfile = /dev/stderr
stdout_logfile_maxbytes = 0
stderr_logfile_maxbytes = 0

[program:firewalld]
command = /bin/firewalld eth0 --bind wan0
autorestart = true
stdout_logfile = /dev/stdout
stderr_logfile = /dev/stderr
stdout_logfile_maxbytes = 0
stderr_logfile_maxbytes = 0

[unix_http_server]
file = /var/run/supervisor.sock
chmod = 0600
chown = root:root
username = supervisorctl
password = supervisorctl

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl = unix:///var/run/supervisor.sock
username = supervisorctl
password = supervisorctl
