name: firewall-checker

services:
  firewall-checker:
    build:
      context: .
      secrets:
        - github-pat
    image: ecsc2025-service-firewall/checker
    pull_policy: never
    container_name: firewall-checker
    restart: unless-stopped
    devices:
      - "/dev/net/tun:/dev/net/tun:rwm"
    cap_add:
      - NET_ADMIN
    ulimits:
      nofile: 65535
    sysctls:
      # Defaults that we always want to set for the VPN client (but can't because procfs is not writable)
      net.ipv4.conf.default.forwarding: 0
      net.ipv4.conf.default.src_valid_mark: 1
      net.ipv6.conf.default.forwarding: 0
      net.ipv6.conf.default.accept_ra: 0
      net.ipv6.conf.default.accept_redirects: 0
      # Settings only for the checker VPN client
      net.ipv4.fwmark_reflect: 1
      net.ipv6.fwmark_reflect: 1
      # Special checker-only settings, not needed for "real" clients (or even for all checks).
      net.ipv6.conf.default.accept_dad: 0 # Adding the VPN address should happen faster
      net.ipv4.conf.all.accept_local: 1 # Needed for loop checking.
    environment:
      MONGO_ENABLED: 1
      MONGO_HOST: firewall-mongodb
      MONGO_PORT: 27017
      MONGO_USER: firewall_checker
      MONGO_PASSWORD: firewall_checker
    depends_on:
      - firewall-mongodb
    ports:
      - "8100:8100/tcp"

  firewall-mongodb:
    image: mongo:8.0.5@sha256:f6164e498dbaee3966031c1ced1bfa0fd1c4961151b38a770fa6994f4b0dcae7
    command: "mongod --port 27017"
    container_name: firewall-mongodb
    restart: unless-stopped
    volumes:
      - type: volume
        source: state-checker
        target: /data/db
    ports:
      - "8101:27017/tcp"
    environment:
      MONGO_INITDB_ROOT_USERNAME: firewall_checker
      MONGO_INITDB_ROOT_PASSWORD: firewall_checker

volumes:
  state-checker:
    name: "ecsc2025-firewall-checker-mongodb"

networks:
  default:
    name: firewall-checker

secrets:
  github-pat:
    environment: GITHUB_PAT
