{
 "title": "Cluster overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "K8s Node",
    "query": {
     "query": "label_values(node_cpu_seconds_total,node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Server Metrics Overview",
   "type": "table",
   "gridPos": { "h": 27, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg by(node) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)"
    },
    {
     "expr": "100 * (1 - ((node_memory_MemAvailable_bytes or node_memory_Buffers_bytes + node_memory_Cached_bytes + node_memory_MemFree_bytes) / node_memory_MemTotal_bytes))"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\"})"
    },
    {
     "expr": "sum by(node) (rate(node_network_receive_bytes_total[5m]))"
    },
    {
     "expr": "sum by(node) (rate(node_network_transmit_bytes_total[5m]))"
    },
    {
     "expr": "max by(node) (kubelet_active_pods{node=~\".+\"})"
    }
   ]
  },
  {
   "title": "Longhorn Volume usage (percentage)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "( (max by (pvc) (longhorn_volume_actual_size_bytes))/ (avg by (pvc) (longhorn_volume_capacity_bytes)) ) *100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Longhorn Volume usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (pvc) (longhorn_volume_actual_size_bytes)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}